project:
  type: website
  output-dir: docs

website:
  title: "Myblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    # other options i like [darkly, lumen, minty, sandstone, spacelab]
    theme: flatly
    css: styles.css



